title: danmuzi.github.io
email: your-email@example.com
description: >- # this means to ignore newlines until 
  My Jekyll-powered GitHub Pages site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danmuzi.github.io" # the base hostname & protocol for your site
theme: minima
