# 사이트 제목
title: 졸업작품 프로젝트명

# 사이트 설명
description: 졸업작품/프로젝트에 대한 간단한 설명을 입력하세요.

# 여러 팀원 이메일을 위한 커스텀 변수
team_emails:
  - member1@example.com
  - member2@example.com
  - member3@example.com

# 저자 또는 팀명
author: 단순 무식 지존

# 사이트 언어
lang: ko

# 배포될 사이트 주소
url: "https://danmuzi.github.io"

# 루트에 배포 시 빈 문자열
baseurl: ""

# 사용할 Jekyll 테마
theme: minima

# 팀원 정보 (필요에 따라 수정)
team_members:
  - name: 김혜령
    role: 단순
  - name: 변우진
    role: 무식
  - name: 심재환
    role: 지존
